Add support for alternate report types
mystatus/covid19-reports pull request #116
Opened 2021-03-04 22:05 UTC by jdgarrett

This PR adds an additional table to store report schemas that can be used by the processor in order to support group-specific report types.  It also allows the user to associate muster windows with a specific type or report.

![image](https://user-images.githubusercontent.com/2428907/110036823-9a31cf80-7d0b-11eb-9fbe-55cf5a42332e.png)
![image](https://user-images.githubusercontent.com/2428907/110036874-aae24580-7d0b-11eb-947e-0e3f6c00ee5e.png)

2021-03-05 21:11 UTC, larskendall requested changes
Looking great! Love seeing those tests get added.

I had just a few notes mostly related to some typings type stuff and possible simplifications.

2021-03-05 21:43 UTC, jdgarrett commented on server/api/report-schema/report-schema.controller.spec.ts
> +      } as ReportBody;
Turns out those were missing an attribute, good catch!

2021-03-05 21:44 UTC, jdgarrett commented on server/api/report-schema/report-schema.controller.ts
> +    if (!req.appOrg || !req.appUserRole) {
I agree that we're pretty inconsistent about these, I removed them from the new code, perhaps we can address this in a future task.

2021-03-05 21:44 UTC, jdgarrett commented on server/api/report-schema/report-schema.model.ts
> +}];
Unfortunately this would require a separate interface, so it's not quite worth it.

2021-03-08 18:37 UTC, larskendall approved these changes

2021-03-09 13:04 UTC, AnthonyWhitaker approved these changes
Good stuff!

2021-03-09 13:04 UTC, AnthonyWhitaker commented on src/components/pages/units-page/edit-unit-dialog.tsx
> +                        <Select
Do we care that the styling of the dropdown doesn't match other `select` controls?

2021-03-09 18:13 UTC, merged