Roster query builder
mystatus/covid19-reports pull request #47
Opened 2020-11-20 19:49 UTC by AnthonyWhitaker

This is one of those tasks I could spend another sprint or two on... committing now due to sprint end.

2020-11-25 22:29 UTC, larskendall requested changes
The functionality is all looking great. There were just a few minor linting type things I noticed.

2020-11-25 22:29 UTC, larskendall commented on src/hooks/use-deep-equality.ts
> +export default function useDeepEquality<T>(value?: T | undefined): [T| undefined, Dispatch < SetStateAction < T| undefined >>, T| undefined] {
The spacing seems a little odd in the return type here. Does this work ok instead?
```typescript
export default function useDeepEquality<T>(value?: T | undefined): [T | undefined, Dispatch<SetStateAction<T | undefined>>, T | undefined] {

```

2020-11-25 22:57 UTC, DaveJackson-PE commented
After seeing a number of lint issues in these reviews, I realized that I needed to install **AND** _**enable**_ the eslint extension in VS Code. Not sure if this is an issue for @AnthonyWhitaker or anyone else on the team, but thought I'd share just in case...

2020-11-25 23:12 UTC, larskendall commented
@DaveJackson-PE Yeah it's best to have eslint flag stuff right in your IDE and/or run eslint manually to check for warnings before submitting a PR. There are still a couple wonky project setup issues that might make it a little awkward to run manually, so it's probably easiest to just rely on the IDE for now until we can make another technical debt pass. Ideally we should also automatically flag them all on GitHub when submitting a PR.

2020-11-26 00:21 UTC, AnthonyWhitaker commented
> After seeing a number of lint issues in these reviews, I realized that I needed to install **AND** _**enable**_ the eslint extension in VS Code. Not sure if this is an issue for @AnthonyWhitaker or anyone else on the team, but thought I'd share just in case...

I do have or enabled. There's something weird about the way vscode or the eslint plugin seems to be handling the nested config for the server. If usually formats in sace and so should have caught the double quotes and any other auto-fixable items. I took a note to look into it but haven't made time.

2020-11-26 02:13 UTC, AnthonyWhitaker commented on server/api/roster/roster.controller.ts
> +    const page = (req.query.page != null) ? parseInt(req.query.page) : 0;
Going to delay this change for now. This code is actually just copy-pasted from getRoster() on line 176 - which is the non-filtered equivalent of this call. I think in the future these should be consolidated or refactored in some other way.

2020-11-26 02:20 UTC, AnthonyWhitaker commented on server/api/roster/roster.controller.ts
> +  static getColumnSelect(column: RosterColumnInfo) {
I can't get my IDE to work with our eslint/tsconfig setup. src/* seems to work but anything in server/ is failing. I'll take a pass at this now - manually but will get WebStorm installed or work on fixing the vscode setup for future changes.

2020-11-26 08:22 UTC, merged