Roster validation and <ErrorBoundary> impl
mystatus/covid19-reports pull request #59
Opened 2020-12-07 19:17 UTC by DaveJackson-PE

Summary of changes
------------------

This PR covers the requirements for the following Asana task:

> [Better input validation and error messages on roster load](https://app.asana.com/0/1188940305683068/1199145504016473)

List of changes
---------------

- Added EDIPI validation - 10 digit integer allowing leading zeros
- Added `value.trim().length` check in addition to `value.length` to `canSave()`
- Implemented `<ErrorBoundary>` component

What code can others reuse?
---------------------------

- `<ErrorBoundary>` 

Should this pull request be tested any more or less than usual?
---------------------------------------------------------------
Usual regression testing on the Roster page for validation and error handling should be sufficient.

What are general test steps or cases?
-------------------------------------

1. On Roster page, click 'UPLOAD CSV' button 
2. Select an invalid file
3. Verify the following error dialog:

![Roster-Upload-CSV-Error](https://user-images.githubusercontent.com/73907006/100760691-a5492c80-33b7-11eb-957b-713231045b67.png)

4. Dismiss the dialog and the list is active again, allowing the user to recover and continue.

2020-12-07 23:08 UTC, larskendall requested changes
I wasn't able to get the dialog to show when I tried triggering an error from the roster edit dialog. Did you confirm it works as expected?

I think the error boundary isn't meant for showing dialogs anyways, so it's probably worth aborting that particular approach and just stripping the Dialog stuff out of ErrorBoundary. The example shown in the React docs shows it being used to replace the normal component tree with a basic component to show an error, so that you show the error right on the element where the normal component would have rendered.

Following the React example, I think the error boundary might be as simple as this...

```typescript
import React, { ReactNode } from 'react';

export interface ErrorBoundaryProps {
  children?: ReactNode,
}

export interface ErrorBoundaryState {
  hasError: boolean
}

export class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = {
      hasError: false,
    };
  }

  static getDerivedStateFromError() {
    // Update state so the next render will show the fallback UI.
    return {
      hasError: true,
    };
  }

  render() {
    if (this.state.hasError) {
      // Render fallback UI.
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children;
  }
}
```

2020-12-07 23:37 UTC, DaveJackson-PE commented on src/components/error-boundary/error-boundary.tsx
> +        <Dialog
Ahhh... yeah I had the linter format the document and it didn't catch that. It didn't look quite right, but I wasn't sure what was off about it. Thanks for the info!

2020-12-08 00:17 UTC, DaveJackson-PE commented on src/components/app.tsx
> +    <ErrorBoundary>
Resolved with latest commit

2020-12-08 00:19 UTC, DaveJackson-PE commented
Running through `<ErrorBoundary>` tests again in production mode to track down the remaining issue

2020-12-08 15:06 UTC, DaveJackson-PE commented
I finally found a decent example of a reasonable `<ErrorBoundary>` implementation and test case. I modified it slightly to show a `<Snackbar><Alert>...` instead of a `<Dialog>` so we can notify the user of the error yet still allow them to recover gracefully. I have a simple test case I'll provide in a separate repo for reference.

2020-12-08 17:41 UTC, larskendall approved these changes
This looks good! I'll go ahead and merge it.

2020-12-08 17:42 UTC, merged